<a href="https://colab.research.google.com/github/Aishwaryaschakote/Aishwaryaschakote/blob/main/AICC_tasks_from_Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 4

In [ ]:
#collections

In [ ]:
lists=['apple', 'banana', 'cherry']
print(len(lists))
print(lists[0])
print(lists[-1])
print(lists[0:2])

3
apple
cherry
['apple', 'banana']


In [ ]:
fruits=['apple', 'banana', 'cherry']
fruits.append('orange')
print(fruits)

#insert at perticular position
fruits.insert(2,'grapes')
print(fruits)

#removing one item banana
fruits.remove('banana')
print(fruits)

#using pop to remove only last item
fruits.pop()
print(fruits)

#using update() to update a item in list
fruits[0]='pineapple'
print(fruits)

['apple', 'banana', 'cherry', 'orange']
['apple', 'banana', 'grapes', 'cherry', 'orange']
['apple', 'grapes', 'cherry', 'orange']
['apple', 'grapes', 'cherry']
['pineapple', 'grapes', 'cherry']


In [ ]:
# storing marks of students
marks=[20,48,55,50,68]
print('highest: ', max(marks))
print('lowest: ', min(marks))
print('total sum: ', sum(marks))
print('average:', sum(marks)/len(marks))


highest:  68
lowest:  20
total sum:  241
average: 48.2


In [ ]:
#person and packing

person=('aish', 22, 'engineering')
name,age,job=person
print(age)
print(name)

22
aish


In [ ]:
#converting tuple into list for updating the tuple

person=('aish', 22, 'engineering')
person1 = list(person)
person1[0]='anju'
person=tuple(person1)
print(person)

('anju', 22, 'engineering')


In [ ]:
#sets

sts={1,2,3,2,1}
print(sts)

{1, 2, 3}


In [ ]:
 marks1=[30,40,40,50]
 new_marks1=set(marks1)
 print(new_marks1)

{40, 50, 30}


In [ ]:
a={1,2,3,4,6}
b={4,5,6}
print(a.union(b))
print(a.intersection(b))


{1, 2, 3, 4, 5, 6}
{4, 6}


In [23]:
students={'name':'Aishwarya', 'id':'012'}
print(students)

#printing the values of dictionaries
print(students['name'])
print(students['id'])

#printing both keys and values of dict
for keys,values in students.items():
  print(keys,values)

#printing only keys
print(students.keys())

#printing only values
print(students.values())

{'name': 'Aishwarya', 'id': '012'}
Aishwarya
012
name Aishwarya
id 012
dict_keys(['name', 'id'])
dict_values(['Aishwarya', '012'])


#task of the day


##student manager: store 5 students names in a list, converts them into a set to remove duplicates, stores each student with marks


In [26]:
stud=['Rahul','shakili','aish','chinna', 'aish']
print("original_list:", stud)

stud_unique=set(stud)
print("unique_list:", stud_unique)

print("new dict")
stud_marks={}

print("taking marks for each student")
for stud in stud_unique:
  markss=int(input(f'enter marks for {stud}:'))
  stud_marks[stud]=markss

print("students scoring above 80: ")

for stud, marks in stud_marks.items():
  if marks>80:
    print(stud)


original_list: ['Rahul', 'shakili', 'aish', 'chinna', 'aish']
unique_list: {'shakili', 'Rahul', 'aish', 'chinna'}
new dict
taking marks for each student
enter marks for shakili:35
enter marks for Rahul:886
enter marks for aish:85
enter marks for chinna:96
students scoring above 80: 
Rahul
aish
chinna


#Day 5

In [1]:
pip install numpy


In [3]:
numbers=[1,2,3,4,5]
print(numbers)

result=[]
for i in numbers:
  result.append(i*2)
print(result)

[1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]


In [9]:
import numpy as np

#1D array
arr=np.array([1,2,3,4,5,6])
print(arr)

#2D Arr(matrix)
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [16]:
arr1=np.array([[[1,2,3],
 [1,2,3],
  [4,5,6]]])
print(arr1)

print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

[[[1 2 3]
  [1 2 3]
  [4 5 6]]]
(1, 3, 3)
3
9


In [18]:
print(arr[0])
print(arr[-1])

1
6
